clickhouse_starschema:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "rc1d-mb0nbushgtr6bvn8.mdb.yandexcloud.net"
      port: 8443
      user: "admin"
      password: "jxtymlkbyysqgfhjkm"
      secure: True
      verify: False
    ci:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: default
      threads: 4
  target: dev
